// double check the addresses

export const coins = {
  TestCoin: {
    name: "test!!!",
    address: "7mHCx9iXPJ7EJDbDAUGmej39Kme8cxZfeVi1EAvEpump",
    keywords: ["is", "the", "in", "he", "she", "it", "they", "we", "you"],
  },
  FREESHLOMO: {
    name: "FREESHLOMO",
    address: "9L1SWjsBFaCeUP9sh9s7wty7n69vTrTPCJx41DcPpump",
    keywords: ["shlomo"],
  },
  BIGBALLS: {
    name: "Edward Coristine",
    address: "7mHCx9iXPJ7EJDbDAUGmej39Kme8cxZfeVi1EAvEpump",
    keywords: ["big balls", "edward coristine", "coristine", "bolz"],
  },
  KM: {
    name: "Kekius Maximus",
    address: "HuAncxDEsakCDgZS2Yfo9xJbHmtHXMnxxkT9jqdXnHhm",
    keywords: ["kekius", "kekius maximus"],
  },
  Pnut: {
    name: "Peanut the Squirrel",
    address: "2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump",
    keywords: ["pnut", "peanut"],
  },
  ADRIAN: {
    name: "Adrian Dittmann",
    address: "6Em4veHJFxfnEvu2cyQhkn2BszvHxycPba8fL3Psx4gY",
    keywords: ["adrian", "dittmann"],
  },
  DOGEFATHER: {
    name: "Dogefather",
    address: "EcYK2XNG4wWr2vDg2M2Hrts6SrU2QB4NzXLBf888pump",
    keywords: ["dogefather"],
  },
  NOLAND: {
    name: "The World's First AI Human",
    address: "D3fQZ6fmHseTCsNntBMnu3Tk3EV3uN68VLDQZWgVpump",
    keywords: ["arbaugh", "neuralink patient"],
  },
  LUIGI: {
    name: "Luigi Mangione",
    address: "5XyKkFaJpAmsH4Tf2EFj3S61W3hC5cJhxNZQQ5h1pump",
    keywords: ["luigi", "mangione"],
  },
  ASSANGE: {
    name: "Julian Assange",
    address: "4FrXUwfQ7zp56N87ac8BX2aqmFoKmvo6Jp7SuTMZpump",
    keywords: ["assange"],
  },
  HARAMBE: {
    name: "HARAMBE",
    address: "Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP",
    keywords: ["harambe"],
  },
  TRUTHGPT: {
    name: "Elon OPENAI NAME",
    address: "DkVoFwo7aQTUeEMSegZgvUoigHti329Fm9wiMvfdpump",
    keywords: ["truthgpt", "truth gpt"],
  },
  GREED3: {
    name: "Greed 3",
    address: "64S7bmFVNZLfaiZVoHzZA5nDDUsssy6KbeVVdD66pump",
    keywords: ["greed3", "greed 3"],
  },
  DDTG: {
    name: "Davey Day Trader Global",
    address: "DVtrerbvaB1JyAKA9crCN2xkxnYD5jBCLgsUrBZEpump",
    keywords: ["$ddtg"],
  },
  JAILSTOOL: {
    name: "Stoole Presidente (jailstool)",
    address: "AxriehR6Xw3adzHopnvMn7GcpRFcD41ddpiTWMg6pump",
    keywords: ["jailstool"],
  },
  SBF: {
    name: "Sam Bankman-Fried",
    address: "9Nuzd5BZMfeiP2TSXXGqYcrtqYEyFkGoEbm39CB3pump",
    keywords: [],
  },
  GREENLAND: {
    name: "America 51st State",
    address: "5JEdwCUafTGLFZz8wDLmWNLbJKKwFafrHJ7A3W1Wpump",
    keywords: ["greenland"],
  },
  HKU5: {
    name: "New China coronavirus",
    address: "HRqNoAHzcvxRwMf64gz9C6DHKW1icgjebjvK23ikpump",
    keywords: ["hku5"],
  },
  SWF: {
    name: "Sovereign Wealth Fund",
    address: "FtBXDMyD4SvAa6keQPAGk4sgRVuUECsxGU1X2dLWpump",
    keywords: ["sovereign wealth fund"],
  },
  TGC: {
    name: "TRUMP GOLD CARDS",
    address: "3LuA7cib588PogacQvxpjWJoon9KoXEGHL4WMroCmnrg",
    keywords: ["trump gold card", "gold card"],
  },
  POPE: {
    name: "Pietro Parolin",
    address: "7rnYT9QqS9RKYFJnDT14T14LxmG1c3xZo61pSVJRpump",
    keywords: ["pietro", "parolin"],
  },
  KNOX: {
    name: "Official Fort Knox Coin",
    address: "4N8g7mw171aVC1oMMRV1pMrQuB1RwFHaJan2WYyBpump",
    keywords: ["knox"],
  },
  BROC: {
    name: "Broccoli",
    address: "D13VkjDiCxtgRJsH4s1VCxKS4bFZq5UEz2iRsSbapump",
    keywords: ["broccoli"],
  },
  ZACK: {
    name: "Zacktardio",
    address: "2mN3yfFwanRmgLVpLWcCskUuyhTr8zKoBw6nwiivpump",
    keywords: ["zacktardio"],
  },
  TRUMPBILL: {
    name: "Trump 250 Bill",
    address: "7nEx3cF6bgD2LDh3MimokRPbAV97TFsGKQyjRKN7pump",
    keywords: ["trump bill", "250 bill", "trump 250", "250 dollarbill"],
  },
  LEAF: {
    name: "Leaf Erikson",
    address: "7vqkjrxbtVazEwREnHB2nv2poYmzr9Yr4KdWp64Bpump",
    keywords: ["leaf", "erikson", "leaf erikson"],
  },
  ROGER: {
    name: "Free Roger",
    address: "4NS4nxNunN7KJ1oe2PRCnh1KbBBut2fTqYHqU7Gtpump",
    keywords: ["free roger", "roger ver"],
  },

  SWASTI: {
    name: "Swasticoin",
    address: "D91JAEfzeFZspHc6PrY8n1p234oEKXzhM3EM73Vppump",
    keywords: ["swasticoin"],
  },
  SWASTA: {
    name: "Swastachain",
    address: "DVzbUXeAQGyDLsn9FkGxm6q2q9hs7tUK4cimmmQpump",
    keywords: ["swastachain"],
  },
  BABYDEER: {
    name: "Baby Deer",
    address: "6pKHwNCpzgZuC9o5FzvCZkYSUGfQddhUYtMyDbEVpump",
    keywords: ["baby deer", "deer"],
  },
};

export const twitterAccounts = [
  // --------- TEST ACCOUNTS ---------
  {
    username: "testCoin",
    name: "testCoin",
    coins: [{ ...coins.TestCoin, amountToBuy: 0.01 }],
  },
  // {
  //   username: "MarioNawfal",
  //   name: "Mario Nawfal (test)",
  //   coins: [{ ...coins.TestCoin, amountToBuy: 0.01 }],
  // },
  // {
  //   username: "nypost",
  //   name: "New York Post (test)",
  //   coins: [{ ...coins.TestCoin, amountToBuy: 0.01 }],
  // },

  // {
  //   username: "ABC",
  //   name: "ABC",
  //   coins: [{ ...coins.TestCoin, amountToBuy: 0.01 }],
  // },
  // {
  //   username: "teslaownersSV",
  //   name: "teslaownersSV",
  //   coins: [{ ...coins.TestCoin, amountToBuy: 0.01 }],
  // },

  // ---------------------------------
  {
    username: "SimonKaggwaNjal",
    name: "Simon Kaggwa Njala",
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 5,
    slippageBpsForAnyPostedCA: 4000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },
  {
    username: "gaysolmeme",
    name: "Gay Sol Meme",
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 5,
    slippageBpsForAnyPostedCA: 4000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },

  {
    username: "stoolpresidente",
    name: "Dave Portnoy",
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 8,
    slippageBpsForAnyPostedCA: 5000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },

  {
    username: "elonmusk",
    name: "Elon Musk",
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 8,
    slippageBpsForAnyPostedCA: 5000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
    coins: [
      { ...coins.BIGBALLS, amountToBuy: 5 },
      { ...coins.KM, amountToBuy: 10 },
      { ...coins.PNUT, amountToBuy: 5 },
      { ...coins.ADRIAN, amountToBuy: 5 },
      { ...coins.DOGEFATHER, amountToBuy: 5 },
      { ...coins.NOLAND, amountToBuy: 5 },
      { ...coins.LUIGI, amountToBuy: 5 },
      { ...coins.ASSANGE, amountToBuy: 5 },
      { ...coins.HARAMBE, amountToBuy: 5 },
      { ...coins.TRUTHGPT, amountToBuy: 3 },
      { ...coins.BABYDEER, amountToBuy: 10 },
      { ...coins.FREESHLOMO, amountToBuy: 10 },
    ],
  },
  {
    username: "stoolpresidente",
    name: "Dave Portnoy",
    coins: [
      { ...coins.GREED3, amountToBuy: 3 },
      { ...coins.DDTG, amountToBuy: 3 },
      { ...coins.JAILSTOOL, amountToBuy: 1 },
    ],
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 8,
    slippageBpsForAnyPostedCA: 5000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },
  // --------- SBF ---------
  // any tweet
  {
    username: "SBF_FTX",
    name: "SBF",
    coins: [{ ...coins.SBF, amountToBuy: 10, automaticBuy: true }],
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 8,
    slippageBpsForAnyPostedCA: 5000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },
  {
    username: "WatcherGuru",
    name: "Watcher Guru",
    coins: [
      { ...coins.GREENLAND, amountToBuy: 3 },
      { ...coins.HKU5, amountToBuy: 3 },
      { ...coins.SWF, amountToBuy: 1 },
      { ...coins.BIGBALLS, amountToBuy: 3 },
      { ...coins.TGC, amountToBuy: 3 },
      { ...coins.POPE, amountToBuy: 4 },
      { ...coins.KNOX, amountToBuy: 3 },
    ],
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 8,
    slippageBpsForAnyPostedCA: 5000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },

  {
    username: "DeItaone",
    name: "Walter Bloomberg",
    coins: [
      { ...coins.GREENLAND, amountToBuy: 3 },
      { ...coins.HKU5, amountToBuy: 3 },
      { ...coins.SWF, amountToBuy: 1 },
      { ...coins.BIGBALLS, amountToBuy: 3 },
      { ...coins.TGC, amountToBuy: 3 },
    ],
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 8,
    slippageBpsForAnyPostedCA: 5000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },
  {
    username: "aeyakovenko",
    name: "toly🇺🇸",
    coins: [],
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 8,
    slippageBpsForAnyPostedCA: 5000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },
  {
    username: "cz_binance",
    name: "CZ",
    coins: [{ ...coins.BROC, amountToBuy: 10 }],
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 8,
    slippageBpsForAnyPostedCA: 5000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },
  {
    username: "MrZackMorris",
    name: "Zack Morris",
    coins: [{ ...coins.ZACK, amountToBuy: 2 }],
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 3,
    slippageBpsForAnyPostedCA: 3000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },
  {
    username: "BNONews",
    name: "BNO News",
    coins: [
      { ...coins.GREENLAND, amountToBuy: 5 },
      { ...coins.HKU5, amountToBuy: 3 },
      { ...coins.SWF, amountToBuy: 1 },
      { ...coins.BIGBALLS, amountToBuy: 3 },
      { ...coins.TGC, amountToBuy: 5 },
      { ...coins.BIGBALLS, amountToBuy: 5 },
      { ...coins.KM, amountToBuy: 10 },
      { ...coins.PNUT, amountToBuy: 5 },
      { ...coins.ADRIAN, amountToBuy: 5 },
      { ...coins.DOGEFATHER, amountToBuy: 5 },
      { ...coins.ASSANGE, amountToBuy: 5 },
      { ...coins.HARAMBE, amountToBuy: 5 },
    ],
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 8,
    slippageBpsForAnyPostedCA: 5000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },
  {
    username: "RealRossU",
    name: "Ross Ulbricht",
    coins: [
      { ...coins.LEAF, amountToBuy: 10 },
      { ...coins.ROGER, amountToBuy: 10 },
    ],
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 8,
    slippageBpsForAnyPostedCA: 5000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },
  {
    username: "kanyewest",
    name: "Kanye West",
    coins: [
      { ...coins.SWASTI, amountToBuy: 3 },
      { ...coins.SWASTA, amountToBuy: 3 },
    ],
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 8,
    slippageBpsForAnyPostedCA: 5000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },
  {
    username: "DavidSacks",
    name: "David Sacks",
    coins: [],
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 8,
    slippageBpsForAnyPostedCA: 5000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },
  {
    username: "davidsacks47",
    name: "David Sacks",
    coins: [],
    buyAnyPostedCA: true,
    amountToBuyForAnyPostedCA: 8,
    slippageBpsForAnyPostedCA: 5000,
    timeToSellForAnyPostedCA: 120 * 1000,
    priorityFeeForAnyPostedCA: 0.1,
  },
];

console.log(JSON.stringify(twitterAccounts, null, 2));
