[build]
  base = "/"
  command = "npm install --prefix frontend-react --no-audit --no-fund && npm run --prefix frontend-react build"
  publish = "frontend-react/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://discord-scraper-t69j.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
